name = "Compression"
author = "Nyagi"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5f1ade2cccc635b6a70a7b0cbe718c68565bc1467b43c51effcb018be179198"

[versions]
forge = "43.3.13"
minecraft = "1.19.2"
