name = "Compression"
author = "Nyagi"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43e6b88c2d133bdeb777d402ba7c242f859bd029130051d2ae6e485cf7e8831f"

[versions]
forge = "43.3.13"
minecraft = "1.19.2"
