name = "Compression"
author = "Nyagi"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eea975e239a1340b72f7e895aac59412e03961203b8da7956fecdd081f7582fc"

[versions]
forge = "43.3.13"
minecraft = "1.19.2"
