name = "Compression"
author = "Nyagi"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6c10c55ac63d47eff4d1e5600646c0c6ff5da3a2bf7baa52acce9a5e9772af2"

[versions]
forge = "43.3.13"
minecraft = "1.19.2"
