name = "Compression"
author = "Nyagi"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fea4950c7147dc83c5c6d4f9b3827f7faa06ae867a0fe435d87f65fd86f0b079"

[versions]
forge = "43.3.13"
minecraft = "1.19.2"
