name = "Compression"
author = "Nyagi"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "102d50c578af792acd673eea0cb2712ca3013c89443ba6ea3df0904a53114527"

[versions]
forge = "43.3.13"
minecraft = "1.19.2"
