name = "Compression"
author = "Nyagi"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "864a983945f1ce8b0ef09f90755c098968dcd2a216138711aafa03660d3028d7"

[versions]
forge = "43.3.13"
minecraft = "1.19.2"
